services:
  mysql-workbench:
    image: petitgens/mysql-workbench:${MYSQL_WORKBENCH_VERSION:-latest}

    environment:
      - DISPLAY=${DISPLAY}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

    restart: no
